### ISSUE TITLE
Bug: RSS link tags

### ISSUE THREAD

**Issue by ysm0622** [SoYoung210/SOSO#16]
https://github.com/SoYoung210/SOSO/blob/4860756041bd83098148d3c5287d51b7e01a8d51/gatsby-meta-config.js#L6

The RSS' link tags are broken because of this config.

https://so-so.dev/rss.xml

![image](https://user-images.githubusercontent.com/18487241/69008492-80da0800-098e-11ea-82ff-5dabeac6659a.png)

**Comment by SoYoung210** [comment]
Oh,, 😱 Thx a lot..! 
It's fix on #18 :)
